app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
①app/assets/stylesheet/application.cssの拡張子変更、記載内容の修正
②app/assets/javascripts/application.jsの追記
=> Create header => Bootstrapの初期設定

app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/users/products/index.html.erb
=> ヘッダー部分テンプレート作成

app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/users/products/index.html.erb
=> Feature product registration

app/assets/stylesheets/order_products.scss, app/assets/stylesheets/orders.scss, app/assets/stylesheets/users.scss, app/controllers/admins/products_controller.rb, app/views/admins/products/edit.html.erb, app/views/admins/products/index.html.erb, app/views/admins/products/show.html.erb
=> Feature admin products

app/controllers/users/deliveries_controller.rb, app/views/admins/products/new.html.erb, app/views/users/deliveries/edit.html.erb, app/views/users/deliveries/index.html.erb, config/routes.rb
配送先一覧画面、編集画面のアクション・ビューそれぞれ実装しました。
=> Feature deliveries

app/controllers/admins/users_controller.rb, app/controllers/users/deliveries_controller.rb, app/views/admins/products/new.html.erb, app/views/admins/users/edit.html.erb, app/views/admins/users/index.html.erb, app/views/admins/users/show.html.erb, app/views/users/deliveries/edit.html.erb, app/views/users/deliveries/index.html.erb, config/routes.rb
=> Feature admin userindex

app/controllers/users/cart_items_controller.rb, app/controllers/users/products_controller.rb, app/models/cart_item.rb, app/views/users/cart_items/index.html.erb, app/views/users/products/show.html.erb, config/routes.rb
・商品詳細からカートへの追加機能は実装済
・カート一覧画面にて、以下の機能が未実装
①destroy_all
②商品の個数変更
③合計金額
=> Feature cart items

app/controllers/admins/orders_controller.rb, app/views/admins/orders/index.html.erb
・注文一覧画面を作成
・controllerで遷移先によってviewに渡す変数を指定
・注文詳細の作成及び一覧画面の確認は、顧客側の注文機能実装時に作成
=> [fix]管理者の注文履歴一覧作成

app/controllers/users/cart_items_controller.rb, app/controllers/users/orders_controller.rb, app/controllers/users/products_controller.rb, app/models/cart_item.rb, app/models/product.rb, app/models/user.rb, app/views/admins/products/edit.html.erb, app/views/admins/products/new.html.erb, app/views/admins/products/show.html.erb, app/views/users/cart_items/index.html.erb, app/views/users/products/index.html.erb, app/views/users/products/show.html.erb, config/routes.rb
=> Feature cart items 2

app/controllers/admins/orders_controller.rb, app/controllers/admins/products_controller.rb, app/views/admins/products/top.html.erb, app/views/admins/users/show.html.erb
注文履歴への遷移できるように修正しました。
また管理者用のTOPページ作成しました。
=> [fix]  注文履歴への遷移機能修正および管理者TOPページ作成

app/assets/stylesheets/users/users.scss, app/controllers/users/users_controller.rb, app/views/users/users/edit.html.erb, app/views/users/users/show.html.erb, app/views/users/users/withdraw_confirm.html.erb, config/routes.rb
・ユーザーの詳細画面、編集画面、退会確認画面の追加
・ユーザーの編集機能、退会機能、退会済ユーザーのブロック機能追加
=> [Fix]　ユーザー画面・編集機能の実装

db/seeds.rb
・仮ユーザーを3名追加
・商品を32種類作成
・1ユーザーに対して注文を1~3回分作成(作成日時は10日以内からランダム作成)
・1ユーザーに対してカート内に商品を3種類追加
・注文の商品は1~5種類をランダムに作成
=> [Update]seedデータの追加

app/assets/stylesheets/admins/genres.scss, app/views/admins/genres/edit.html.erb, app/views/admins/genres/index.html.erb
・ステータスの変更が反映されない不具合を修正
・一覧で状態が表示されない不具合を修正
・デザインをフレームワークに合わせ修正
=> [Update]Genre不具合修正・デザイン調整

app/controllers/admins/genres_controller.rb, app/controllers/admins/order_products_controller.rb, app/controllers/admins/orders_controller.rb, app/controllers/admins/products_controller.rb, app/controllers/admins/users_controller.rb, app/views/admins/products/edit.html.erb, app/views/admins/products/new.html.erb, app/views/admins/registrations/new.html.erb, app/views/admins/sessions/new.html.erb
・管理者側のログイン前アクション制限
・管理者ページへのアクセス制限
・管理者側のエラーメッセージ表示を追加
=> Admin confirm

app/controllers/users/deliveries_controller.rb, app/controllers/users/orders_controller.rb, app/models/delivery.rb, app/models/order.rb, app/models/order_product.rb, app/views/users/orders/confirm.html.erb, app/views/users/orders/confirmation.html.erb, app/views/users/orders/index.html.erb, app/views/users/orders/new.html.erb, app/views/users/orders/show.html.erb, app/views/users/orders/thanks.html.erb, config/routes.rb, db/seeds.rb
注文機能実装
/新しい配送先を選んだ際のアクション未記述
/enumの表記直す必要あり
/データベースの値を確認する必要あり
/validation未実装
//余力があったらissue記載のオーダー無限生成についてorder.controllerにupdateアクションを追加
=> Feature order

app/controllers/users/deliveries_controller.rb
コミットメッセージの通り、配送先情報の画面表示を修正しました。
=> [fix] ログインユーザの配送先情報のみ表示されるように修正

app/assets/javascripts/application.js, app/assets/stylesheets/admins/genres.scss, app/controllers/admins/order_products_controller.rb, app/controllers/admins/orders_controller.rb, app/models/order.rb, app/models/order_product.rb, app/views/admins/orders/index.html.erb, app/views/admins/orders/show.html.erb, config/routes.rb
・遷移先のページによって注文履歴の変数を作成(最終調整)
・注文詳細画面を作成
・ルート及びJSの記載を変更
=> [Update]管理者側の注文一覧画面作成

app/assets/stylesheets/users/products.scss, app/controllers/admins/products_controller.rb, app/controllers/users/products_controller.rb, app/views/admins/products/edit.html.erb, app/views/admins/products/index.html.erb, app/views/admins/products/new.html.erb, app/views/admins/products/show.html.erb, app/views/users/products/_recommend_item.html.erb, app/views/users/products/_search_bar.html.erb, app/views/users/products/top.html.erb, app/views/users/products/top.js.erb, db/migrate/20200509130701_add_recommend_to_products.rb, db/schema.rb
・レイアウトが未調整部分もありますが、TOPページ作成しました
・TOPページ表示に際してレコメンド機能が必要でしたので追加しました
=> Feature recommend

app/assets/stylesheets/admins/genres.scss, app/assets/stylesheets/admins/orders.scss, app/assets/stylesheets/admins/users.scss, app/controllers/admins/orders_controller.rb, app/controllers/admins/products_controller.rb, app/controllers/admins/users_controller.rb, app/controllers/users/products_controller.rb, app/views/admins/genres/index.html.erb, app/views/admins/orders/index.html.erb, app/views/admins/orders/show.html.erb, app/views/admins/products/_form.html.erb, app/views/admins/products/edit.html.erb, app/views/admins/products/index.html.erb, app/views/admins/products/new.html.erb, app/views/admins/products/show.html.erb, app/views/admins/products/top.html.erb, app/views/admins/sessions/new.html.erb, app/views/admins/users/edit.html.erb, app/views/admins/users/index.html.erb, app/views/admins/users/show.html.erb, app/views/kaminari/_first_page.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/users/products/index.html.erb, config/initializers/kaminari_config.rb
=> [Update]管理者ページの修正

app/models/delivery.rb, app/models/order.rb, app/models/user.rb
=> Validation

app/controllers/users/orders_controller.rb, app/models/order.rb, app/models/order_product.rb, app/views/admins/orders/index.html.erb, app/views/admins/orders/show.html.erb, app/views/users/orders/edit.html.erb, app/views/users/orders/index.html.erb, app/views/users/orders/new.html.erb, app/views/users/orders/show.html.erb, db/seeds.rb
=> Fix total price

db/seeds.rb
=> [Fix]seedsデータバリデーションチェック

app/controllers/users/products_controller.rb, app/views/users/cart_items/index.html.erb, app/views/users/products/_search_bar.html.erb, app/views/users/products/index.html.erb, app/views/users/products/top.html.erb, config/routes.rb
=> [Update]商品のジャンル検索機能を作成

app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb, app/views/users/shared/_links.html.erb
=> User view login/signup

app/views/admins/sessions/new.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb
コミットメッセージの通りです。
少しだけadminsの方のログインもusers側との整合性をとるために修正しました、勝手にいじって申し訳ないですたっくん。
=> [Update]ログイン関連の画面のデザイン手直しと同時に整合性とりました。

app/assets/stylesheets/application.scss, app/controllers/users/products_controller.rb, app/views/users/cart_items/index.html.erb, app/views/users/orders/confirmation.html.erb, app/views/users/orders/index.html.erb, app/views/users/products/_recommend_item.html.erb, app/views/users/products/index.html.erb
#81 対応しました。
同時にテーブルの縦方向の中央寄せ及びactiveで表示切り替えもやりました。
=> Fix layout images

README.md
=> [update]  README更新

app/controllers/admins/products_controller.rb, app/views/admins/genres/index.html.erb, app/views/admins/orders/index.html.erb, app/views/admins/orders/show.html.erb, app/views/admins/products/_form.html.erb, app/views/admins/products/index.html.erb, app/views/admins/products/index_all.html.erb, app/views/admins/products/show.html.erb, app/views/admins/users/index.html.erb, config/routes.rb
=> Feature admin recommend

app/views/layouts/_header.html.erb
=> [Update]ヘッダーの表示崩れ修正
